-- MySQL Script generated by MySQL Workbench
-- 09/23/15 22:06:51
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema newtwitter
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema newtwitter
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `newtwitter` DEFAULT CHARACTER SET latin1 ;
USE `newtwitter` ;

-- -----------------------------------------------------
-- Table `newtwitter`.`user_`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `newtwitter`.`user_` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `username` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `email` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `password_hash` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `status` SMALLINT(6) NOT NULL COMMENT '',
  `auth_key` VARCHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `password_reset_token` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '',
  `account_activation_token` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '',
  `created_at` INT(11) NOT NULL COMMENT '',
  `updated_at` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `username` (`username` ASC)  COMMENT '',
  UNIQUE INDEX `email` (`email` ASC)  COMMENT '',
  UNIQUE INDEX `password_reset_token` (`password_reset_token` ASC)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `newtwitter`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `newtwitter`.`article` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `user_id` INT(11) NOT NULL COMMENT '',
  `title` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `summary` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `content` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `status` INT(11) NOT NULL COMMENT '',
  `category` INT(11) NOT NULL COMMENT '',
  `created_at` INT(11) NOT NULL COMMENT '',
  `updated_at` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `user_id` (`user_id` ASC)  COMMENT '',
  CONSTRAINT `article_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `newtwitter`.`user_` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `newtwitter`.`auth_rule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `newtwitter`.`auth_rule` (
  `name` VARCHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `data` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '',
  `created_at` INT(11) NULL DEFAULT NULL COMMENT '',
  `updated_at` INT(11) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`name`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `newtwitter`.`auth_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `newtwitter`.`auth_item` (
  `name` VARCHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `type` INT(11) NOT NULL COMMENT '',
  `description` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '',
  `rule_name` VARCHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '',
  `data` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '',
  `created_at` INT(11) NULL DEFAULT NULL COMMENT '',
  `updated_at` INT(11) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`name`)  COMMENT '',
  INDEX `rule_name` (`rule_name` ASC)  COMMENT '',
  INDEX `idx-auth_item-type` (`type` ASC)  COMMENT '',
  CONSTRAINT `auth_item_ibfk_1`
    FOREIGN KEY (`rule_name`)
    REFERENCES `newtwitter`.`auth_rule` (`name`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `newtwitter`.`auth_assignment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `newtwitter`.`auth_assignment` (
  `item_name` VARCHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `user_id` INT(11) NOT NULL COMMENT '',
  `created_at` INT(11) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`item_name`, `user_id`)  COMMENT '',
  CONSTRAINT `auth_assignment_ibfk_1`
    FOREIGN KEY (`item_name`)
    REFERENCES `newtwitter`.`auth_item` (`name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `newtwitter`.`auth_item_child`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `newtwitter`.`auth_item_child` (
  `parent` VARCHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `child` VARCHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  PRIMARY KEY (`parent`, `child`)  COMMENT '',
  INDEX `child` (`child` ASC)  COMMENT '',
  CONSTRAINT `auth_item_child_ibfk_1`
    FOREIGN KEY (`parent`)
    REFERENCES `newtwitter`.`auth_item` (`name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `auth_item_child_ibfk_2`
    FOREIGN KEY (`child`)
    REFERENCES `newtwitter`.`auth_item` (`name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `newtwitter`.`migration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `newtwitter`.`migration` (
  `version` VARCHAR(180) NOT NULL COMMENT '',
  `apply_time` INT(11) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`version`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `newtwitter`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `newtwitter`.`posts` (
  `post_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `post_value` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `post_date` INT(11) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`post_id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `newtwitter`.`post_post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `newtwitter`.`post_post` (
  `postOnet_id` INT(11) NOT NULL COMMENT '',
  `postsTwo_id` INT(11) NOT NULL COMMENT '',
  INDEX `fk_post_post_posts_idx` (`postOnet_id` ASC)  COMMENT '',
  INDEX `fk_post_post_posts1_idx` (`postsTwo_id` ASC)  COMMENT '',
  CONSTRAINT `fk_post_post_posts`
    FOREIGN KEY (`postOnet_id`)
    REFERENCES `newtwitter`.`posts` (`post_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_post_posts1`
    FOREIGN KEY (`postsTwo_id`)
    REFERENCES `newtwitter`.`posts` (`post_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `newtwitter`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `newtwitter`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `username` VARCHAR(25) NOT NULL COMMENT '',
  `email` VARCHAR(255) NOT NULL COMMENT '',
  `password_hash` VARCHAR(60) NOT NULL COMMENT '',
  `auth_key` VARCHAR(32) NOT NULL COMMENT '',
  `confirmed_at` INT(11) NULL DEFAULT NULL COMMENT '',
  `unconfirmed_email` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  `blocked_at` INT(11) NULL DEFAULT NULL COMMENT '',
  `role` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  `registration_ip` BIGINT(20) NULL DEFAULT NULL COMMENT '',
  `created_at` INT(11) NOT NULL COMMENT '',
  `updated_at` INT(11) NOT NULL COMMENT '',
  `flags` INT(11) NOT NULL DEFAULT '0' COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `user_unique_username` (`username` ASC)  COMMENT '',
  UNIQUE INDEX `user_unique_email` (`email` ASC)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `newtwitter`.`profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `newtwitter`.`profile` (
  `user_id` INT(11) NOT NULL COMMENT '',
  `name` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  `public_email` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  `gravatar_email` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  `gravatar_id` VARCHAR(32) NULL DEFAULT NULL COMMENT '',
  `location` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  `website` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  `bio` TEXT NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`user_id`)  COMMENT '',
  CONSTRAINT `fk_user_profile`
    FOREIGN KEY (`user_id`)
    REFERENCES `newtwitter`.`user` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `newtwitter`.`session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `newtwitter`.`session` (
  `id` CHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `expire` INT(11) NOT NULL COMMENT '',
  `data` LONGBLOB NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `newtwitter`.`social_account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `newtwitter`.`social_account` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `user_id` INT(11) NULL DEFAULT NULL COMMENT '',
  `provider` VARCHAR(255) NOT NULL COMMENT '',
  `client_id` VARCHAR(255) NOT NULL COMMENT '',
  `data` TEXT NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `account_unique` (`provider` ASC, `client_id` ASC)  COMMENT '',
  INDEX `fk_user_account` (`user_id` ASC)  COMMENT '',
  CONSTRAINT `fk_user_account`
    FOREIGN KEY (`user_id`)
    REFERENCES `newtwitter`.`user` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `newtwitter`.`token`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `newtwitter`.`token` (
  `user_id` INT(11) NOT NULL COMMENT '',
  `code` VARCHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `created_at` INT(11) NOT NULL COMMENT '',
  `type` SMALLINT(6) NOT NULL COMMENT '',
  UNIQUE INDEX `token_unique` (`user_id` ASC, `code` ASC, `type` ASC)  COMMENT '',
  CONSTRAINT `fk_user_token`
    FOREIGN KEY (`user_id`)
    REFERENCES `newtwitter`.`user_` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
